# Sprint 02. Tasca 01
## By José Manuel Castaño

## Exercici 1

Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.

In [2]:
import numpy as np
from numpy import random
arr = np.array([random.randint(20)for i in range(8)], dtype ='int64')
print(arr)
print("La dimensió de la array és: {0}".format(arr.ndim))
print("la forma de la array és: {0}".format(arr.shape))

[ 4  7 13 11 16 12 18  6]
La dimensió de la array és: 1
la forma de la array és: (8,)


## Exercici 2

De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [10]:
mitjana = arr.mean()
arr - mitjana


array([-1.125, -1.125,  2.875,  2.875,  0.875,  2.875, -6.125, -1.125])

## Exercici 3

Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.

In [5]:
matriu = random.randint(0, 50, (5,5))
print(matriu)

print("El valor màxim de la matriu és: {0}".format(matriu.max()))

print("Els valors màxims de l'eix 0 és: {0}".format(matriu.max(axis=0)))

print("Els valors màxims de l'eix 1 és: {0}".format(matriu.max(axis=1)))



[[27 12 42 25 37]
 [38 38 43 32 30]
 [30 28 26  2 40]
 [46  5 44 18 30]
 [32 18 24 15 29]]
El valor màxim de la matriu és: 46
Els valors màxims de l'eix 0 és: [46 38 44 32 40]
Els valors màxims de l'eix 1 és: [42 43 40 46 32]
